// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcI_7_hOfRhWGR6kC6Wta20ImCgk2j_qE',
    appId: '1:1026156429605:web:55178083e748ba634c1acc',
    messagingSenderId: '1026156429605',
    projectId: 'ivecon-f9b6f',
    authDomain: 'ivecon-f9b6f.firebaseapp.com',
    storageBucket: 'ivecon-f9b6f.appspot.com',
    measurementId: 'G-Z86NFJP046',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ2rbWIgyMnLyfg6miczb7-vPjI4yeStQ',
    appId: '1:1026156429605:android:568419352793bfac4c1acc',
    messagingSenderId: '1026156429605',
    projectId: 'ivecon-f9b6f',
    storageBucket: 'ivecon-f9b6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBRrmIodvu6wL5tv7toxz1VAL7bP7rj_w',
    appId: '1:1026156429605:ios:9e0c6e3d83debea24c1acc',
    messagingSenderId: '1026156429605',
    projectId: 'ivecon-f9b6f',
    storageBucket: 'ivecon-f9b6f.appspot.com',
    iosClientId: '1026156429605-3codo0au655bsqs2jvdavn4r0hirunvv.apps.googleusercontent.com',
    iosBundleId: 'com.example.ivecon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBRrmIodvu6wL5tv7toxz1VAL7bP7rj_w',
    appId: '1:1026156429605:ios:bc584e40695b71324c1acc',
    messagingSenderId: '1026156429605',
    projectId: 'ivecon-f9b6f',
    storageBucket: 'ivecon-f9b6f.appspot.com',
    iosClientId: '1026156429605-5qmf6d48rn23m244cejs9hh7dsb3gcul.apps.googleusercontent.com',
    iosBundleId: 'com.example.ivecon.RunnerTests',
  );
}
